### ISSUE TITLE
EmptyRecycle calls undefined method from OC dav app

### ISSUE THREAD

**Issue by mirekys** [sciencemesh/oc-sciencemesh#4] opened 2022-10-07 10:22 UTC
Running on `bitnami/owncloud:latest` docker image, but with: https://github.com/pondersource/core (reva-sharees branch) used for owncloud core sources, calling EmptyRecycle API fails with:

```json
{
  "reqId": "pae6ytFPQ6ZIfL74tPuj",
  "level": 3,
  "time": "2022-10-07T09:47:20+00:00",
  "remoteAddr": "10.10.231.204",
  "user": "--",
  "app": "index",
  "method": "POST",
  "url": "/index.php/apps/sciencemesh/~test/api/storage/EmptyRecycle",
  "message": {
    "Exception": "Error",
    "Message": "Call to undefined method OCA\\DAV\\TrashBin\\TrashBinManager::listTrashRoot()",
    "Code": 0,
    "Trace": [
      "#0 /opt/bitnami/owncloud/lib/private/AppFramework/Http/Dispatcher.php(170): OCA\\ScienceMesh\\Controller\\RevaController->EmptyRecycle()",
      "#1 /opt/bitnami/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController()",
      "#2 /opt/bitnami/owncloud/lib/private/AppFramework/App.php(100): OC\\AppFramework\\Http\\Dispatcher->dispatch()",
      "#3 /opt/bitnami/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\AppFramework\\App::main()",
      "#4 /opt/bitnami/owncloud/lib/private/Route/Router.php(344): OC\\AppFramework\\Routing\\RouteActionHandler->__invoke()",
      "#5 /opt/bitnami/owncloud/lib/base.php(928): OC\\Route\\Router->match()",
      "#6 /opt/bitnami/owncloud/index.php(54): OC::handleRequest()",
      "#7 {main}"]
    "File": "/opt/bitnami/owncloud/apps/sciencemesh/lib/Controller/RevaController.php",
    "Line": 462
  }
}
```

There seems to be no such function like `listTrashRoot ` in the recent implementations of [TrashBinManager](https://github.com/owncloud/core/blob/v10.10.0/apps/dav/lib/TrashBin/TrashBinManager.php)

**Comment by labkode** [comment] 2022-10-17 08:19
Hi @mirekys, I understand this is an issue however I don't see why this is a blocker for the ScienceMesh roadmap.

**Comment by mirekys** [comment] 2022-10-17 12:40
> Hi @mirekys, I understand this is an issue however I don't see why this is a blocker for the ScienceMesh roadmap.

Hi @labkode I brought it there, as it is a most visible cause of constantly failing Filesystem OPs monitoring probes (testing just a basic FS ops) for our ScienceMesh site. It seems that this issue is being triggered by an ordinary file delete request (as seen here coming from the `sciencemesh-hcheck-fs-operations` monitoring probe), thus basic file deletion also (probably) fails.

```
2022-10-17 12:29:04.038 INF src/github/cs3org/reva/pkg/storage/fs/nextcloud/nextcloud.go:279 > Delete {"path":"/home/fsoperations"} pid=1 pkg=rgrpc traceid=b4fcc08cb95aca008268ea3ab35bbf46
2022-10-17 12:29:04.038 INF src/github/cs3org/reva/pkg/storage/fs/nextcloud/nextcloud.go:212 > nc.do req https://oc-mesh.du.cesnet.cz/index.php/apps/sciencemesh/~test/api/storage/Delete {"path":"/home/fsoperations"} pid=1 pkg=rgrpc traceid=b4fcc08cb95aca008268ea3ab35bbf46
metrics pid=1 pkg=rhttp
2022-10-17 12:29:04.24 INF src/github/cs3org/reva/pkg/storage/fs/nextcloud/nextcloud.go:231 > nc.do res https://oc-mesh.du.cesnet.cz/index.php/apps/sciencemesh/~test/api/storage/Delete <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-requesttoken="">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
					<meta name="apple-itunes-app" content="app-id=1359583808">
				<meta name="theme-color" content="#041e42">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#041e42">
					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/styles.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/inputs.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/header.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/icons.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/fonts.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/apps.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/global.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/fixes.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/multiselect.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/mobile.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/tooltip.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/share.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/apps/firstrunwizard/css/colorbox.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/apps/firstrunwizard/css/firstrunwizard.css?v=76f17c7e0ec0a626d236220de4d83aec">
					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=76f17c7e0ec0a626d236220de4d83aec">
									<script src="/core/vendor/jquery/dist/jquery.min.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/underscore/underscore.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/moment/min/moment-with-locales.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/handlebars/handlebars.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/blueimp-md5/js/md5.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/bootstrap/js/tooltip.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/backbone/backbone.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/es6-promise/es6-promise.auto.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/davclient.js/lib/client.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/clipboard/dist/clipboard.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/bowser/src/bowser.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/jquery.ocdialog.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/oc-dialogs.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/js.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/l10n.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/octemplate.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/eventsource.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/config.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/search/js/search.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/oc-requesttoken.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/apps.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/mimetype.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/mimetypelist.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/snapjs/dist/latest/snap.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/vendor/select2/select2.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/oc-backbone.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/oc-backbone-webdav.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/placeholder.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/jquery.avatar.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/shareconfigmodel.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharemodel.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharescollection.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/shareitemmodel.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialogresharerinfoview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialoglinklistview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialoglinkshareview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialogmailview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialoglinksocialview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialoglinkexpirationview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialogshareelistview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/sharedialogview.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/share.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/user.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/apps/files_mediaviewer/js/files_mediaviewer_init.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/apps/firstrunwizard/js/jquery.colorbox.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/apps/firstrunwizard/js/firstrunwizard.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/files/fileinfo.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					<script src="/core/js/files/client.js?v=76f17c7e0ec0a626d236220de4d83aec"></script>
					</head>
	<body id="body-login"  >
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank" rel="noreferrer">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
		<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									ownCloud								</h1>
							</div>
							<div id="logo-claim" style="display:none;"></div>
						</div>
					</header>
								<span class="error error-wide">
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.</p>
		<p>More details can be found in the <a target="_blank" rel="noreferrer" href="https://doc.owncloud.com/server/10.10/go.php?to=admin-logfiles">server log</a>.</p>
	<br>

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: xxxx</li>
		<li>Request ID: OZAXXuYBR50o4cN0DiW6</li>
			</ul>

	</span>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://owncloud.com" target="_blank" rel="noreferrer">ownCloud</a> &ndash; A safe home for all your data			</p>
		</footer>
	</body>
</html>
 pid=1 pkg=rgrpc traceid=b4fcc08cb95aca008268ea3ab35bbf46
2022-10-17 12:29:04.241 DBG src/github/cs3org/reva/internal/grpc/interceptors/log/log.go:66 > unary code=OK end="17/Oct/2022:12:29:04 +0000" from=tcp://xxxxxx:56219 pid=1 pkg=rgrpc start="17/Oct/2022:12:29:04 +0000" time_ns=202812603 traceid=b4fcc08cb95aca008268ea3ab35bbf46 uri=/cs3.storage.provider.v1beta1.ProviderAPI/Delete user-agent=grpc-go/1.47.0
```

In addition, note the `OK` response to file `Delete` GRPC call, even though the nextcloud storage driver returned a `HTTP 500` HTML error page because of the PHP error above

**Comment by labkode** [comment] 2022-10-17 13:04
@mirekys thanks, that was the context I was missing, so yes, it makes sense to fix this issue. 
@michielbdejong can you please assign this issue in your team? Thanks

**Comment by michielbdejong** [comment] 2022-10-19 07:12
OK, the issue of seeing an 'OK' response is fixed in https://github.com/cs3org/reva/pull/3369/files#diff-50ddb55a0dd8bb38c82ffd8ba0b62151298b24b7255aab11822264204111c224R234
Now investigating the issue itself.

The TrashBinManager exists, and it is in the OCA\DAV\TrashBin namespace: https://github.com/owncloud/core/blob/master/apps/dav/lib/TrashBin/TrashBinManager.php
The RevaController has a `use OCA\DAV\TrashBin\TrashBinManager;` statement at the top.
Instead of a `listTrashRoot` function, there is a `getChildren` function.
There is also a `deleteAll` function which might be even easier.

**Comment by michielbdejong** [comment] 2022-10-19 07:16
Hm, it looks like `deleteAll` may be for all users, checking.
Ah no, it's [only for the current user](https://github.com/owncloud/core/blob/v10.10.0/apps/files_trashbin/lib/Trashbin.php#L646).
OK, let's use that then.

**Comment by michielbdejong** [comment] 2022-10-19 07:25
Steps to reproduce using an ocm-test-suite testnet on mesh.pondersource.org:
```
ssh root@mesh.pondersource.org
cd ocm-test-suite
./scripts/clean.sh
./scripts/start-from-Revaoc.sh
docker exec -it revaoc1.docker /reva/cmd/reva/reva -insecure -host localhost:19000
login basic
einstein
relativity
recycle-purge
exit
docker logs revaoc1.docker
```

**Comment by michielbdejong** [comment] 2022-10-19 07:28
Without my fix it shows:
```
error: code=CODE_INTERNAL msg="error emptying recycle:Unexpected response code from EFSS API: 500" support_trace="97a00823f72d09d8573cde608a0244cc"
```
in reva-cli and this in the revad logs:
```
2022-10-19 07:29:02.887 INF ../../reva/pkg/storage/fs/nextcloud/nextcloud.go:546 > EmptyRecycle pid=8 pkg=rgrpc traceid=145966406bf4d16aecde7cb481352ab3
2022-10-19 07:29:02.888 INF ../../reva/pkg/storage/fs/nextcloud/nextcloud.go:213 > nc.do req https://oc1.docker/index.php/apps/sciencemesh/~einstein/api/storage/EmptyRecycle  pid=8 pkg=rgrpc traceid=145966406bf4d16aecde7cb481352ab3
2022-10-19 07:29:03.061 INF ../../reva/pkg/storage/fs/nextcloud/nextcloud.go:232 > nc.do res https://oc1.docker/index.php/apps/sciencemesh/~einstein/api/storage/EmptyRecycle <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-requesttoken="">
[...]
	<h2><strong>Internal Server Error</strong></h2>
		<p>The server encountered an internal error and was unable to complete your request.</p>
		<p>Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.</p>
		<p>More details can be found in the <a target="_blank" rel="noreferrer" href="https://doc.owncloud.com/server/10.11/go.php?to=admin-logfiles">server log</a>.</p>
	<br>

	<h2><strong>Technical details</strong></h2>
	<ul>
		<li>Remote Address: 172.31.0.2</li>
		<li>Request ID: 5dOpHvpaD4r0hXGq61mS</li>
			</ul>

	</span>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://owncloud.com" target="_blank" rel="noreferrer">ownCloud</a> &ndash; A safe home for all your data			</p>
		</footer>
	</body>
</html>
 pid=8 pkg=rgrpc traceid=145966406bf4d16aecde7cb481352ab3
2022-10-19 07:29:03.061 ERR ../../reva/internal/grpc/services/storageprovider/storageprovider.go:932 > failed to empty recycle error="Unexpected response code from EFSS API: 500" key= pid=8 pkg=rgrpc reference={} status={"code":15,"message":"error emptying recycle:Unexpected response code from EFSS API: 500","trace":"97a00823f72d09d8573cde608a0244cc"} traceid=145966406bf4d16aecde7cb481352ab3
```

It now gives no error in reva-cli and this in revad logs:
```
2022-10-19 07:26:50.975 INF ../../reva/pkg/storage/fs/nextcloud/nextcloud.go:213 > nc.do req https://oc1.docker/index.php/apps/sciencemesh/~einstein/api/storage/EmptyRecycle  pid=8 pkg=rgrpc traceid=1864dab989527fdb21dcae638d13d7fb
2022-10-19 07:26:51.197 INF ../../reva/pkg/storage/fs/nextcloud/nextcloud.go:232 > nc.do res https://oc1.docker/index.php/apps/sciencemesh/~einstein/api/storage/EmptyRecycle "OK" pid=8 pkg=rgrpc traceid=1864dab989527fdb21dcae638d13d7fb
```

**Closed as completed** 2022-10-19 07:32 UTC
